### ISSUE TITLE
No Proper CSS for backups for windows phone

### ISSUE THREAD

**Issue by rubyAce71697** [prabhakar267/whatsapp-reader#7]
I don't know whether the backups for android and windows phone is stored in different way, but the website is not working properly for windows phone WhatsApp backup

**Comment by AnirudhGoel** [comment]
Can you please upload a sample chat of windows phone so that the app can be optimized for that ?

**Comment by prabhakar267** [comment]
@rubyAce71697  actually whatsapp-reader is not for reading the backup files
You can email your chats to other people and it is used to read those emailed text files.

I will surely consider to include the backups too.

**Comment by rubyAce71697** [comment]
The file sent as email is different in case of windows phone (that format is not generic). I have forked your repo and made it compatible with the windows phone file. Also I have updated the UI (little bit) to reflect to the group chats in proper manner.  The code has to me made proper, after doing that I will send you the merge request and you can check before meaning.
